### ISSUE TITLE
viewport not resizing

### ISSUE THREAD

**Issue by bhoffpauir** [LegatAbyssWalker/Escape#1]
You can use the Event::Resized event to resize the glViewport might not work with the state machine though.

**Comment by LegatAbyssWalker** [comment]
To resize the window you mean?

**Comment by bhoffpauir** [comment]
well when you try to maximize the window the opengl viewport won't change with  ends up being in the bottom corner of the screen at the original width & height so if you could `case Event::Resized: glViewport(0,0,event.width, event.height); break;`

**Comment by LegatAbyssWalker** [comment]
Fixed. Should be up in a second.
